In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Convert NumPy array to Tensor
def tf_constant(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        tensorflow.python.framework.ops.EagerTensor: tensor.
    """
    tf_constant_array = tf.constant(array)
    return tf_constant_array

In [3]:
tmp_array = np.arange(1,10)
x = tf_constant(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [4]:
# Square the input tensor
def tf_square(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        EagerTensor: tensor.
    """
    array = tf.constant(array)
    tf_squared_array = tf.square(array)
    return tf_squared_array

In [5]:
tmp_array = tf.constant(np.arange(1, 10))
x = tf_square(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [6]:
# Reshape tensor
def tf_reshape(array, shape):
    """
    Args:
        array (EagerTensor): tensor to reshape.
        shape (tuple): desired shape.

    Returns:
        EagerTensor: reshaped tensor.
    """
    array = tf.constant(array)
    tf_reshaped_array = tf.reshape(array, shape=shape)
    return tf_reshaped_array

In [7]:
tmp_array = np.array([1,2,3,4,5,6,7,8,9])
x = tf_reshape(tmp_array, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [8]:
# Cast tensor to a new type
def tf_cast(array, dtype):
    """
    Args:
        array (EagerTensor): tensor to be casted.
        dtype (tensorflow.python.framework.dtypes.DType): desired new type. (Should be a TF dtype!)

    Returns:
        EagerTensor: casted tensor.
    """
    array = tf.constant(array)
    tf_cast_array = tf.cast(array, dtype)
    return tf_cast_array

In [9]:
tmp_array = [1,2,3,4]
x = tf_cast(tmp_array, tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [10]:
# Multiply tensors
def tf_multiply(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    product = tf.multiply(tensor1, tensor2)
    return product

In [11]:
tmp_1 = tf.constant(np.array([[1,2],[3,4]]))
tmp_2 = tf.constant(np.array(2))
result = tf_multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

In [12]:
# Add tensors
def tf_add(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    total = tf.add(tensor1, tensor2)
    return total

In [13]:
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6 ]))
tf_add(tmp_1, tmp_2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

In [14]:
# Gradient Tape
def tf_gradient_tape(x):
    """
    Args:
        x (EagerTensor): a tensor.

    Returns:
        EagerTensor: Derivative of z with respect to the input tensor x.
    """
    with tf.GradientTape() as t:
        # Record the actions performed on tensor x
         t.watch(x)

        # Define a polynomial of form 3x^3 - 2x^2 + x
         y = tf.pow(x, 3)*3-tf.square(x)*2+x

        # Obtain the sum of the elements
         z = tf.reduce_sum(y)
  
    dz_dx = t.gradient(z, x)
    return dz_dx

In [15]:
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

29.0